### ISSUE TITLE
Building Docker Image Fails

### ISSUE THREAD

**Issue by barryfx** [PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition#1]
Building the very first docker image as instructed in the book in Windows 11 fails during the "conda init bash" command.  As a result, the bioinformatics_base conda environment doesn't load.  When you connect to the jupyter lab server none of the conda packages are available.  Running the docker image results in an error saying that conda init hadn't been run for the shell.  I tried this from both a powershell and cmd prompt.

**Comment by tiagoantao** [comment]
Hi,

I am going to have a look at this during the weekend, I will get back to you soon.

**Comment by tiagoantao** [comment]
@barryfx Could you please put the error here? I cannot replicate it.
You also consider pulling it from docker hub instead with: `docker pull tiagoantao/bio3`

**Comment by barryfx** [comment]
The error is when you run the image...

(base) PS D:\projects\BioCookbook> docker run -p 9875:9875 -v
/projects/BioCookbook:/data bio

CommandNotFoundError: Your shell has not been properly configured to use
'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running
'conda init'.


[W 2022-11-16 16:09:19.211 LabApp] 'token' has moved from NotebookApp to
ServerApp. This config will be passed to ServerApp. Be sure to update your
config before our next release.
[W 2022-11-16 16:09:19.211 LabApp] 'password' has moved from NotebookApp to
ServerApp. This config will be passed to ServerApp. Be sure to update your
config before our next release.
[I 2022-11-16 16:09:19.216 ServerApp] jupyterlab | extension was
successfully linked.
[I 2022-11-16 16:09:19.224 ServerApp] Writing notebook server cookie secret
to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-11-16 16:09:19.414 ServerApp] nbclassic | extension was
successfully linked.
[W 2022-11-16 16:09:19.456 ServerApp] All authentication is disabled.
Anyone who can connect to this server will be able to run code.
[I 2022-11-16 16:09:19.460 LabApp] JupyterLab extension loaded from
/opt/conda/lib/python3.8/site-packages/jupyterlab
[I 2022-11-16 16:09:19.460 LabApp] JupyterLab application directory is
/opt/conda/share/jupyter/lab
[I 2022-11-16 16:09:19.462 ServerApp] jupyterlab | extension was
successfully loaded.
[I 2022-11-16 16:09:19.466 ServerApp] nbclassic | extension was
successfully loaded.
[I 2022-11-16 16:09:19.467 ServerApp] Serving notebooks from local
directory: /Bioinformatics-with-Python-Cookbook-third-Edition
[I 2022-11-16 16:09:19.467 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2022-11-16 16:09:19.467 ServerApp] http://c7b0a938e6a8:9875/lab
[I 2022-11-16 16:09:19.467 ServerApp]  or http://127.0.0.1:9875/lab
[I 2022-11-16 16:09:19.467 ServerApp] Use Control-C to stop this server and
shut down all kernels (twice to skip confirmation).

-----------------------------------------------------------------------------------------------------------------------------------------


When I connect to Jupyter Labs the packages are missing because the
environment failed to be activated.  It looks like this...

[image: image.png]

**Comment by tiagoantao** [comment]
I just updated the images. Even if the `conda init` issue persists, the jupyter lab is working here.
Note that if you going to use the R code you need to get `tiagoantao/bioinformatics_r` and not `tiagoantao/bio3`

**Comment by barryfx** [comment]
Confirmed.  It looks like it worked on my end.  I didn't get the conda init
issue either.
Thanks

**Comment by tiagoantao** [comment]
Sorry for taking so much time to sort this out.
Feel free to open other tickets if you find problems. I will try to be faster
