### ISSUE TITLE
Plink issue in chapter_06

### ISSUE THREAD

**Issue by JunJieHe520** [PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition#5]
Hi, Tiago Antao:
      I am using Ubuntu 20.04 and Python 3.8 (anaconda). When I run the code 
'data = plink.read_plink(path = 'hapmap10_auto_noofs_ld', fam_sep='\t')' in jupyter lab,
it gives me an error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[51], line 1
----> 1 data = plink.read_plink(path = 'hapmap10_auto_noofs_ld', fam_sep='\t')

File ~/miniconda3/envs/jupyter/lib/python3.8/site-packages/sgkit/io/plink/plink_reader.py:256, in read_plink(path, bed_path, bim_path, fam_path, chunks, fam_sep, bim_sep, bim_int_contig, count_a1, lock, persist)
    253     df_fam = df_fam.persist()
    254     df_bim = df_bim.persist()
--> 256 arr_fam = dataframe_to_dict(df_fam, dtype=FAM_ARRAY_DTYPE)
    257 arr_bim = dataframe_to_dict(df_bim, dtype=BIM_ARRAY_DTYPE)
    259 # Load genotyping data

File ~/miniconda3/envs/jupyter/lib/python3.8/site-packages/sgkit/io/utils.py:38, in dataframe_to_dict(df, dtype)
     35 kind = np.dtype(dt).kind
     36 if kind in ["U", "S"]:
     37     # Compute fixed-length string dtype for array
---> 38     max_len = int(max_str_len(a))
     39     dt = f"{kind}{max_len}"
     40 arrs[c] = a.astype(dt)

File ~/miniconda3/envs/jupyter/lib/python3.8/site-packages/dask/array/core.py:1879, in Array.__int__(self)
   1878 def __int__(self):
-> 1879     return self._scalarfunc(int)

File ~/miniconda3/envs/jupyter/lib/python3.8/site-packages/dask/array/core.py:1876, in Array._scalarfunc(self, cast_type)
   1874     raise TypeError("Only length-1 arrays can be converted to Python scalars")
   1875 else:
-> 1876     return cast_type(self.compute().item())

AttributeError: 'int' object has no attribute 'item'

And I use the exactly same code as you, I try to upgrade or downgrade the sgkit library, but I encounter the same error. I'm looking forward to your response.

**Comment by rahul-packt** [comment]
Hi @tiagoantao, could you please us with this issue?

**Comment by tiagoantao** [comment]
I am a bit delayed with this, but I will have a look this week

**Comment by tiagoantao** [comment]
OK, finally I got to the bottom of this.
This is not related to the book code, but the sgkit code is broken.
There is currently no _released_ version of sgkit that works, but you can get a development version that will work:

`pip install "sgkit[plink] @ git+https://github.com/pystatgen/sgkit@72ba77697fe1ca975dc5761a0a9c4355e5e49419"`

I updated the documentation to reflect this
