### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nimua** [PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition#7]
Chapter05/Low_Quality

# !wget https://vectorbase.org/common/downloads/Current_Release/AgambiaePEST/fasta/data/VectorBase-57_AgambiaePEST_Genome.fasta -O gambiae.fa

# !wget https://vectorbase.org/common/downloads/Current_Release/AatroparvusEBRO/fasta/data/VectorBase-57_AatroparvusEBRO_Genome.fasta -O atroparvus.fa

404: Not Found

**Comment by tiagoantao** [comment]
Apologies for the delay in answering, this is now corrected
