### ISSUE TITLE
Where can I download examples datasets?

### ISSUE THREAD

**Issue by shaghayeghsoudi** [PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition#9]
Hello,
I just recently purchased the third edition of Bioinformatics with python cookbook and I want to practice  examples codes with the data. I could not find the datasets you have used in the book. Is there any link to download the dataset?
Thank for your response in advance

**Comment by tiagoantao** [comment]
The datasets are referred in the sources of for each chapter, for example You can find the sources for the first chapter in:

https://github.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition/blob/main/Chapter01/Interfacing_R.py

and so on...
